[package]
name = "lifegraph"
version = "0.1.0"
authors = ["Piotr Czarnecki <pioczarn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
rocket_contrib = "0.4"
serde = "1"
serde_derive = "1"
